### ISSUE TITLE
Error in t.default(combined_data@assays$RNA@counts) :    argument is not a matrix

### ISSUE THREAD

**Issue by heisar310** [czarnewski/b_cell_in_mucosal_healing#1]
```
> #Compute the relative expression of each gene per cell
> rel_expression <- t( t(combined_data@assays$RNA@counts) / Matrix::colSums(combined_data@assays$RNA@counts)) * 100
Error in t.default(combined_data@assays$RNA@counts) : 
  argument is not a matrix
```
I was running code, "02_Epithelial_Stromal_scRNAseq.Rmd", and coming across this error. How can I fix this? Please, any help would be appreciated.

**Comment by czarnewski** [comment]
Hi @heisar310 . The issue is that the library `Matrix` is lot loaded. This package is used to work on sparse matrices in R. Just running `library(Matrix)` should do it :)
I also added that line on the tutorial. Thanks for let me know!
